### PR TITLE
fix(ci): cover alkanes-cli-common, and stop publishing twice per merge

### PR DESCRIPTION
**Pull request by 0xcasuwu**
Follow-up to #292. That one made CI *run*; this one points it at the right things.

> ### ⚠️ Correction (2026-08-06) — scope reduced, read before merging
>
> An earlier version of this description claimed this PR fixes `develop`'s missing CI. **It does not, and cannot.** A workflow only takes effect from the branch it lives on, so a `main`-targeted edit to `rust.yml`'s triggers does nothing for pushes or PRs to `develop` until it reaches `develop`. flex caught this; the `branches: [main, develop]` change here is necessary but not sufficient, and a **fresh develop-cut branch** is the right mechanism. That work is separate and in flight.
>
> What this PR actually delivers is items 2 and 3 below. Item 1 is groundwork only.

## 1. `develop` added to the trigger list (groundwork — see correction above)

`rust.yml` was gated to `branches: [main]` while `publish-npm.yml` publishes `@alkanes/ts-sdk` from **`develop`** — the branch that ships was the branch nothing tested. This adds `develop` to both trigger lists so the workflow is correct *once it lives on that branch*.

## 2. `alkanes-cli-common` was in no matrix leg

It is compiled **into** the published WASM — provider, coin selection, `execute` — the crate every consumer's transactions are built by. No leg ran a line of it: not its 284 tests, not even a type-check of its test cfg.

That is the direct reason a `TweakedKeypair::to_keypair` compile error sat on `main` (bitcoin 0.32 renamed it `to_inner`) with three green checks above it, and the reason #291's green checks execute none of the code #291 changes.

New leg: `cargo test -p alkanes-cli-common --lib`.

## 3. Every merge published twice

`publish-npm.yml` fired on both `push: develop` and `pull_request: [closed]`. The build is not reproducible, so the two tarballs differ. `latest` resolves to whichever job finished last, and the dist-tag step is `continue-on-error`, so the drift is silent.

Removed the `pull_request` trigger: a closed PR that merged **is** a push to develop, and one that did not merge should never have published. The job's `github.event_name == 'push' || (pull_request && merged)` guard became unreachable and went with it.

## Expect `develop` to go red once CI reaches it

~739 commits ahead of `main`, never tested. Anything that surfaces is a standing finding this workflow could not previously report — not a regression from this PR.

## Not in scope

`publish-npm.yml` still has **no test gate** — it publishes without running the suite. Worth fixing; bundling it here would make the trigger change harder to review.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by kungfuflex** [comment]
Reviewed this independently (I had converged on the same two fixes before seeing it — I've since narrowed #294 to only the publish gate and the dist-tag `continue-on-error`, which this PR deliberately leaves out, so they shouldn't collide: your hunks are the trigger block and the `if:` line, mine are the new job and the dist-tag step).

The change is sound. `--lib` is the right call for exactly the reason you'd hit otherwise — the integration targets under `crates/alkanes-cli-common/tests/` don't compile (`EnhancedExecuteParams` / `SendParams` / `ProtoruneOutpointResponse` gained fields without callers being updated, `alkanes::protorunes::{BalanceSheet, AlkaneId, Balances}` moved, `MockProvider::set_protorunes_response` is gone), and roughly half that directory is already parked as `*.rs.bak`.

**One blocking ordering issue.** This PR targets `main`, and the new leg is red on arrival there. Running the exact command on each tree:

| tree | `cargo test -p alkanes-cli-common --lib --target x86_64-unknown-linux-gnu` |
|---|---|
| `origin/main` (this PR's base) | **fails to compile** |
| this PR's head (`e178bef`) | **fails to compile** — workflow-only diff, so same as base |
| #291 head | green — **284 passed** |
| `origin/develop` | green — 271 passed |

```
error[E0599]: no method named `to_keypair` found for struct `TweakedKeypair` in the current scope
error: could not compile `alkanes-cli-common` (lib) due to 1 previous error; 95 warnings emitted
```

That's the same `to_keypair` error your matrix comment cites — but the fix for it lives in #291, not here, so merging this into `main` on its own turns "Alkanes CLI Common Tests" permanently red until #291 lands.

The 284 figure matches #291's head exactly, which suggests that's where it was measured. On `main` proper the crate doesn't build at all.

So the two PRs are mutually dependent: **#291 needs this leg to be worth anything, and this leg needs #291's fix to be green.** They should land together — either merge #291 first, or merge this into #291's branch so its checks go green on its own code. Sequencing is the operator's call, not mine; flagging it so it isn't discovered post-merge.

Two smaller notes:

- **The red "Protorune Unit Tests" on this PR is not real.** It failed at `Set up job` ("Failed to resolve action download info"), the ~16:30 Actions incident — not your change.
- The 07-31 postmortem's remediation #1 (every job must require `head.repo.full_name == github.repository`) still isn't applied to either workflow here. Adding `pull_request: develop` widens what runs on fork PRs. `rust.yml` handles no secrets so the exposure is small, but it's now a deliberate choice rather than an oversight, and it's worth a separate decision since the guard would stop fork PRs being tested at all.

**Review by kungfuflex — DISMISSED** [review]
Reviewed the diff in full; approving so only CI stands between this and merge.

rust.yml: adding develop to push + pull_request is the right fix and the comment states the reason correctly — publish-npm.yml ships from develop, rust.yml covered only main, so the branch that ships was the branch nothing tested.

The Alkanes CLI Common Tests leg is the substantive part. That crate is compiled into the published WASM and nothing ran a line of it, which is how a TweakedKeypair::to_keypair compile error sat on main under three green checks. Noting the scope for the record: --lib, so 284 unit tests, not integration tests. Real coverage where there was none, not blanket coverage.

publish-npm.yml: removing the pull_request:[closed] trigger is correct — every merge fired both it and push:develop, and since the build is not byte-reproducible the two tarballs differ, so 'latest' landed on whichever finished last while the dist-tag step is continue-on-error. Dropping the now-unreachable if: guard rather than leaving it to imply a trigger that no longer exists is the right call.

Still open and deliberately out of scope here, not blocking: a test gate before publish, and continue-on-error on the dist-tag step.

Note on the current red: Protorune Unit Tests failed at 'Set up job' with 'Failed to resolve action download info. Error: Service Unavailable', retrying ~5.5 minutes before giving up. That is the GitHub Actions incident, not this PR. Re-run is on attempt 3 and currently queued.

**Comment by kungfuflex** [comment]
@0xcasuwu — two things on this one.

**1. The red `Alkanes CLI Common Tests` leg here is stale, not a real failure.** That run started `2026-08-06T16:30:30Z`; #291, which carries the `TweakedKeypair::to_keypair` → `to_inner` fix, merged to `main` at `19:20:50Z` — about three hours later. So the run was testing pre-fix `main`, and the `E0599` in its log is precisely the error #291 fixed. `main` now has `to_inner` at `mock_provider.rs:466`. This needs a re-run, not a code change. I have not re-run it because **Actions is in a major outage** (incident open since `15:22Z`; no runs dispatched in this repo since `17:10Z`).

**2. Your change is now also on a develop-targeted PR: #297.** Since a workflow only governs the branch it lives on, this PR gives `main` the coverage but leaves `develop` — the branch that actually publishes the SDK — with none. #297 ports the same three changes to `develop` and credits you; it is your change, just moved to where it fires. This PR still stands on its own for `main`, and the plan is to keep it targeting `main`.

One thing #297 needed that this PR does not: #292's `cargo install wasm-bindgen-cli --locked`. `develop`'s `rust.yml` predates that fix, and an earlier attempt to turn on develop CI without it (`38e68ab`) failed **all four legs** at `Install test runner` — `time@0.3.55` wants rustc 1.88 against the repo's 1.86 pin — so nothing ran at all.

Also, for the record so nobody "fixes" it later: the `to_keypair`/`to_inner` split between the branches is real and must stay. `main`'s lock resolves `bitcoin` 0.32.5 (`to_inner`), `develop`'s resolves 0.32.7 (`to_keypair`). Verified on `develop`: `cargo test -p alkanes-cli-common --lib` → `271 passed; 0 failed`.

Your call was right, by the way — turning CI on over 739 untested commits is going to surface things. Better to see them.
